name: Release & Publish to NPM
on: 
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20.12.0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun i
      - name: Initialize Git user
        run: |
            git config --global user.email "codebase65@outlook.com"
            git config --global user.name "GH releases"
      - name: Initialize NPM Auth
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env: 
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Release package
        run: bun run release --ci
        env:
          NEXUS_AUTH: ${{secrets.NEXUS_AUTH}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}


      - name: End message
        run: echo 'done'
